
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class CakeBill extends javax.swing.JFrame {

    /**
     * Creates new form CakeBill
     */
    public CakeBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonFruit = new javax.swing.JButton();
        jButtonYB = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonDF = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonRV = new javax.swing.JButton();
        jButtonCarrot = new javax.swing.JButton();
        jButtonSponge = new javax.swing.JButton();
        jButtonChiffon = new javax.swing.JButton();
        jButtonAF = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonUD = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonLB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButtonPrint = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonPay = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTax = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPayment = new javax.swing.JComboBox<>();
        jTextCash = new javax.swing.JTextField();
        jTextChange = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFruit.setBackground(new java.awt.Color(255, 153, 153));
        jButtonFruit.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonFruit.setText("Fruit Cake");
        jButtonFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFruitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFruit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 140, 130));

        jButtonYB.setBackground(new java.awt.Color(255, 153, 153));
        jButtonYB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButtonYB.setText("Yellow Butter Cake");
        jButtonYB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYBActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonYB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        jButtonG.setBackground(new java.awt.Color(255, 153, 153));
        jButtonG.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonG.setText("Genoise Cake");
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 130));

        jButtonDF.setBackground(new java.awt.Color(255, 153, 153));
        jButtonDF.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonDF.setText("Devil's Food Cake");
        jButtonDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 130));

        jButtonP.setBackground(new java.awt.Color(255, 153, 153));
        jButtonP.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonP.setText("Pound Cake");
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 130));

        jButtonRV.setBackground(new java.awt.Color(255, 153, 153));
        jButtonRV.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonRV.setText("Red Velvet Cake");
        jButtonRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRVActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 130));

        jButtonCarrot.setBackground(new java.awt.Color(255, 153, 153));
        jButtonCarrot.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonCarrot.setText("Carrot Cake");
        jButtonCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrotActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCarrot, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 140, 130));

        jButtonSponge.setBackground(new java.awt.Color(255, 153, 153));
        jButtonSponge.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonSponge.setText("Sponge Cake");
        jButtonSponge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpongeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSponge, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 130));

        jButtonChiffon.setBackground(new java.awt.Color(255, 153, 153));
        jButtonChiffon.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonChiffon.setText("Chiffon Cake");
        jButtonChiffon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiffonActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChiffon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, 130));

        jButtonAF.setBackground(new java.awt.Color(255, 153, 153));
        jButtonAF.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonAF.setText("Angel Food Cake");
        jButtonAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 140, 130));

        jButtonF.setBackground(new java.awt.Color(255, 153, 153));
        jButtonF.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonF.setText("Flourless Cake");
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 140, 130));

        jButtonUD.setBackground(new java.awt.Color(255, 153, 153));
        jButtonUD.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButtonUD.setText("Upside Down Cake");
        jButtonUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 140, 130));

        jButtonH.setBackground(new java.awt.Color(255, 153, 153));
        jButtonH.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButtonH.setText("Hummingbird Cake");
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, 130));

        jButtonO.setBackground(new java.awt.Color(255, 153, 153));
        jButtonO.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButtonO.setText("Opera Cake");
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 140, 130));

        jButtonLB.setBackground(new java.awt.Color(255, 153, 153));
        jButtonLB.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButtonLB.setText("Lady Baltimore Cake");
        jButtonLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLBActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 140, 130));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 90));

        jButtonC.setBackground(new java.awt.Color(204, 204, 255));
        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 80, 90));

        jButtonDot.setBackground(new java.awt.Color(204, 204, 255));
        jButtonDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 90));

        jButton0.setBackground(new java.awt.Color(204, 204, 255));
        jButton0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 90));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 90));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 90));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 90));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, 90));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, 90));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 90));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 90));

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 90));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 390, 130));

        jButtonPrint.setBackground(new java.awt.Color(0, 102, 102));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("Print");
        jButtonPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 40));

        jButtonExit.setBackground(new java.awt.Color(0, 102, 102));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Exit");
        jButtonExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 390, 30));

        jButtonReset.setBackground(new java.awt.Color(0, 102, 102));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 40));

        jButtonRemove.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRemove.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemove.setText("Remove");
        jButtonRemove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 40));

        jButtonPay.setBackground(new java.awt.Color(0, 102, 102));
        jButtonPay.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButtonPay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPay.setText("Pay");
        jButtonPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 410, 170));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setText("Sub Total");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel2.setText("Tax");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel3.setText("Total");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jTextSubTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 23, 230, 30));

        jTextTax.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextTax.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, 30));

        jTextTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 170));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 390, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel5.setText("Cash");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel6.setText("Change");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jComboBoxPayment.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBoxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash ", "Visa Card", "Master Card" }));
        jComboBoxPayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(jComboBoxPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 23, 180, 30));

        jTextCash.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextCash.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(jTextCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 63, 180, 30));

        jTextChange.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextChange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(jTextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 180, 30));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 400, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //================================Function==================================
    
    public void ItemCost()
    {
        double sum = 0;
        
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        jTextSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jTextSubTotal.getText());
        
        double cTax = (cTotal1 * 3.5)/100;
        String iTaxTotal = String.format("Rs %.2f", cTax);
        jTextTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("Rs %.2f", cTotal1);
        jTextSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("Rs %.2f", cTotal1 + cTax);
        jTextTotal.setText(iTotal);
        
    }
    
    //============================Function Change===============================
    
    public void Change()
    {
        double sum = 0;
        double tax = 2.5;
        double cash = Double.parseDouble(jTextCash.getText());
        
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        
        double cTax = (sum * tax)/100;
        double cChange = (cash - (sum + cTax));
        
        String changeGiven = String.format("RS %.2f", cChange);
        jTextChange.setText(changeGiven);
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton1.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton1.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        
         jTextCash.setText("");
         jTextChange.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        
         if(! jTextCash.getText().contains("."))
         {
             jTextCash.setText(jTextCash.getText() + jButtonDot.getText()); 
         }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFruitActionPerformed
        
        double PriceOfItem = 800;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Fruit cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFruitActionPerformed

    private void jButtonChiffonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiffonActionPerformed
        
        double PriceOfItem = 1200;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Chiffon cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonChiffonActionPerformed

    private void jButtonAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAFActionPerformed
        
        double PriceOfItem = 1500;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Angel food cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonAFActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        
        double PriceOfItem = 1000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Flourless cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUDActionPerformed
        
        double PriceOfItem = 1350;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Upside down cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonUDActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        
        double PriceOfItem = 790;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Hummingbird cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        
        double PriceOfItem = 1250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Opera cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonOActionPerformed

    private void jButtonLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLBActionPerformed
        
        double PriceOfItem = 2100;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Lady baltimore cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonLBActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Printing progress");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
       catch(java.awt.print.PrinterException e)
       {
           System.err.format("No printer found", e.getMessage());
       }
        
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton7.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton7.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton8.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton8.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton9.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton9.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton4.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton4.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton5.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton5.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
        String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton6.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton6.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton2.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton2.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton3.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton3.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        
         String Enternumber = jTextCash.getText();
        
        if(Enternumber == "")
        {
            jTextCash.setText(jButton0.getText());
        }
        else
        {
            Enternumber = jTextCash.getText() + jButton0.getText();
            jTextCash.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonYBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYBActionPerformed
        
        double PriceOfItem = 900;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Yellow butter cake", "1", PriceOfItem});
        ItemCost();
        
    }//GEN-LAST:event_jButtonYBActionPerformed

    private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
        
        double PriceOfItem = 960;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Pound cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonPActionPerformed

    private void jButtonRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRVActionPerformed
        
        double PriceOfItem = 2000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Red velvet cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonRVActionPerformed

    private void jButtonCarrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrotActionPerformed
        
        double PriceOfItem = 1000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Carrot cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonCarrotActionPerformed

    private void jButtonSpongeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpongeActionPerformed
        
        double PriceOfItem = 1100;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Sponge cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonSpongeActionPerformed

    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        
        double PriceOfItem = 2500;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Genoise cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonGActionPerformed

    private void jButtonDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDFActionPerformed
       
        double PriceOfItem = 2700;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new  Object[]{"Devil's food cake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDFActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jTextChange.setText("");
        jTextTax.setText("");
        jTextTotal.setText("");
        jTextSubTotal.setText("");
        jTextCash.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if(RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        if(jComboBoxPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
            jTextChange.setText("");
            jTextCash.setText("");
        }
        
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private JFrame frame;
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        
        frame = new JFrame("Exit");
        
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want exit", "Point of sale", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakeBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAF;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCarrot;
    private javax.swing.JButton jButtonChiffon;
    private javax.swing.JButton jButtonDF;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonFruit;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonLB;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonRV;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSponge;
    private javax.swing.JButton jButtonUD;
    private javax.swing.JButton jButtonYB;
    private javax.swing.JComboBox<String> jComboBoxPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCash;
    private javax.swing.JTextField jTextChange;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
